### PR TITLE
Simplify dict key/value setting

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by xordoquy** [comment]
Thanks for the pull request. Though it looks good, I'm not willing to change code for the sake of it.
Is there a reason beside style ?

**Comment by frewsxcv** [comment]
There's no reason to use `update` since you're only setting one key/value pair. It results in your code being less indented (PEP8) and more elegant. If beauty and elegance are not desired in your codebase, carry on.

**Comment by dcramer** [comment]
I dont really care either way (this change is trivial, and just changes the git blame which makes it wasteful), but this doesn't make it "more elegant" and it doesn't change it from "not PEP8 to PEP8", the code is already PEP8 compliant.

**Comment by frewsxcv** [comment]
Woops, I meant PEP 20

> Flat is better than nested.

**Pull request closed without merging**
